# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-02 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacienteprofile',
            name='Foto',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='pacienteprofile',
            name='Respuesta',
            field=models.CharField(default='', max_length=300),
        ),
    ]
